export const operationNames = {
  GET_INPUT_FIELDS_CREATE_NEW_USER_REQUEST:
    "GET_INPUT_FIELDS_CREATE_NEW_USER_REQUEST",
  POST_CREATE_NEW_USER_REQUEST: "POST_CREATE_NEW_USER_REQUEST",
};

export const apiCallInitConsts = {
  GET_INPUT_FIELDS_CREATE_NEW_USER_CALL_INIT: "GET_INPUT_FIELDS_CREATE_NEW_USER_CALL_INIT",
  GET_ANY_USER_DETAIL_BY_USER_ID_INIT:"GET_ANY_USER_DETAIL_BY_USER_ID_INIT"
}
export const successConsts = {
  GET_INPUT_FIELDS_CREATE_NEW_USER_SUCCESS:
    "GET_INPUT_FIELDS_CREATE_NEW_USER_SUCCESS",
  GET_ANY_USER_DETAIL_BY_USER_ID_SUCCESS:"GET_ANY_USER_DETAIL_BY_USER_ID_SUCCESS",
};
export const errorConsts = {
  CREATE_USER_REQUEST_BODY_INVALID: "CREATE_USER_REQUEST_BODY_INVALID",
};

export const GET_CREATE_NEW_USER_FORM_ADMIN =
  "GET_CREATE_NEW_USER_INPUT_FIELDS";
export const INITIATE_CREATE_NEW_USER = "INITIATE_CREATE_NEW_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const GET_CREATE_NEW_USER_FORM = "GET_CREATE_NEW_USER_FORM";
export const INITIATE_GET_CREATE_NEW_USER_INPUT_FIELDS =
  "INITIATE_GET_CREATE_NEW_USER_INPUT_FIELDS";
export const GET_CREATE_NEW_USER_FORM_INPUT_FIELDS_SUCCESS =
  "GET_CREATE_NEW_USER_INPUT_FIELDS_SUCCESS";
export const GET_CREATE_NEW_USER_FORM_INPUT_FIELDS_FAILURE =
  "GET_CREATE_NEW_USER_FORM_INPUT_FIELDS_FAILURE";
