export const operationNames = {
  GET_INPUT_FIELDS_CREATE_NEW_USER_REQUEST:
    "GET_INPUT_FIELDS_CREATE_NEW_USER_REQUEST",
  POST_CREATE_NEW_USER_REQUEST: "POST_CREATE_NEW_USER_REQUEST",
};
export const messageTypes = {
  SUCCESS: "SUCCESS",
  LOADING: "LOADING",
  FAILURE: "FAILURE",
  NOT_CALLED: "NOT_CALLED",
};
export const config = {
  headers: {
    "Content-Type": "application/json",
  },
};

export const API_STATUS = {
  SUCCESS: "SUCCESS",
  LOADING: "LOADING",
  FAILURE: "FAILURE",
  NOT_CALLED: "NOT_CALLED",
};

export const apiCallInitConsts = {
  GET_INPUT_FIELDS_CREATE_NEW_USER_CALL_INIT:
    "GET_INPUT_FIELDS_CREATE_NEW_USER_CALL_INIT",
  GET_ANY_USER_DETAIL_BY_USER_ID_INIT: "GET_ANY_USER_DETAIL_BY_USER_ID_INIT",
  POST_UPDATE_USER_DETAILS_INIT: "POST_UPDATE_USER_DETAILS_INIT",
  DELETE_USER_DETAILS_INIT: "DELETE_USER_DETAILS_INIT",
};

export const successConsts = {
  GET_INPUT_FIELDS_CREATE_NEW_USER_SUCCESS:
    "GET_INPUT_FIELDS_CREATE_NEW_USER_SUCCESS",
  GET_ANY_USER_DETAIL_BY_USER_ID_SUCCESS:
    "GET_ANY_USER_DETAIL_BY_USER_ID_SUCCESS",
  POST_UPDATE_USER_DETAILS_SUCCESS: "POST_UPDATE_USER_DETAILS_SUCCESS",
};

export const errorConsts = {
  CREATE_USER_REQUEST_BODY_INVALID: "CREATE_USER_REQUEST_BODY_INVALID",
  POST_UPDATE_USER_DETAILS_FAILURE: "POST_UPDATE_USER_DETAILS_FAILURE",
};

export const requestType = {
  POST: "POST",
  GET: "GET",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
};

export const ManageUserDataConstants = {
  UserListDetails: {
    UPDATE_ACTIVE_PAGE_NUMBER: "UPDATE_ACTIVE_PAGE_NUMBER",
    FETCH_ACTIVE_PAGE_DATA_INIT : "FETCH_ACTIVE_PAGE_DATA_INIT",
    FETCH_ACTIVE_PAGE_DATA_RESPONSE: "FETCH_ACTIVE_PAGE_DATA_RESPONSE",
  },
};

export const GET_CREATE_NEW_USER_FORM_ADMIN =
  "GET_CREATE_NEW_USER_INPUT_FIELDS";
export const INITIATE_CREATE_NEW_USER = "INITIATE_CREATE_NEW_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const GET_CREATE_NEW_USER_FORM = "GET_CREATE_NEW_USER_FORM";
export const INITIATE_GET_CREATE_NEW_USER_INPUT_FIELDS =
  "INITIATE_GET_CREATE_NEW_USER_INPUT_FIELDS";
export const GET_CREATE_NEW_USER_FORM_INPUT_FIELDS_SUCCESS =
  "GET_CREATE_NEW_USER_INPUT_FIELDS_SUCCESS";
export const GET_CREATE_NEW_USER_FORM_INPUT_FIELDS_FAILURE =
  "GET_CREATE_NEW_USER_FORM_INPUT_FIELDS_FAILURE";
